server:
  port: 8080


spring:
#  main:
#    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/llm?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123321
    driver-class-name: com.mysql.cj.jdbc.Driver

langchain4j:
  openai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-638f7b118bde4766b686310eeb1d2d18
      model-name: deepseek-chat
      temperature: 0.7
      max-tokens: 1000
      timeout: 60s
      log-requests: true
      log-responses: true
      strict-tools: true
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-638f7b118bde4766b686310eeb1d2d18
      model-name: deepseek-chat
      temperature: 0.7
      max-tokens: 1000
      timeout: 60s
      log-requests: true
      strict-tools: true
      log-responses: true


# 可通过显式布线模式 来指定要使用模型 ，通过 model-name 来区分
# 使用示例：

#  @AiService(wiringMode = EXPLICIT, chatModel = "openAiChatModel")
#  interface OpenAiAssistant {
#
#  @SystemMessage("You are a polite assistant")
#  String chat(String userMessage);
#}
#
#  @AiService(wiringMode = EXPLICIT, chatModel = "ollamaChatModel")
#  interface OllamaAssistant {
#
#  @SystemMessage("You are a polite assistant")
#  String chat(String userMessage);
#}
#  本地模型部署
#  ollama:
#    chat-model:
#      base-url: http://localhost:11434
#      model-name: deepseek-r1:7b
#      log-requests: true
#      log-responses: true



mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/xml/*.xml
  global-config:
    # ??????
    db-config:
      # ???
      logic-not-delete-value: 0
      # ???
      logic-delete-value: 1
logging:
  level:
    root: info
